language: scala
env:
 - ACTIVATOR_VERSION=1.2.10
 before_script:
 - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
 - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
script: activator-${ACTIVATOR_VERSION}-minimal/activator test